id: PC09FDDD5
initial_creation_type: input
source_metadata:
  title: Mahāmudrā Series
  language: zh
  description: 'Lotsawa House presents the following texts on the subject of Mahāmudrā
    (phyag chen) or the ''Great Seal'':'
  volume:
    2f00a94b8aca431899e57fe99affd696:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    8c7a6fcb0a2e42e9b2851ac295b8ba75:
      title: Mahāmudrā Preliminaries, Main Part & Conclusion
      parent: Advice
    7d19983f27fd4a4597390590dd9cc882:
      title: 'Mahāmudrā: the Swift Way to Become a Lord of Realization'
      parent: Advice
    7685a10f43e34bfdae1a5afe8b776dcb:
      title: The Kusāli's Instruction on the Nature of Mind
      parent: Advice
    38ddd046e9bd43a1a97ac0f7ff626de8:
      title: A Way of Settling into the Realization of Mind’s Essence
      parent: Advice
    16203d791f324c7cbd017854bb2e1273:
      title: 'From the Mahāmudrā Preliminary Practices: Continuous Integration with
        Ground, Path, and Fruition'
      parent: Advice
    fc37039e7bc0449dbc5254571c9af021:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    6ab10b78193c4bb9b06b37f66e04e515:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    7dbb8090409c47aba85c01d7bc73fcea:
      title: The Mahāmudrā Practice of Stillness, Movement and Awareness
      parent: Advice
    785f06a888cc45578a997d81bc4cd21a:
      title: Instructions on the Fivefold Mahāmudrā
      parent: Advice
    7289fb7dce47448e97948ba5285b1b1b:
      title: Pointing Out Instruction
      parent: Advice
    001d451db151445dbea367bdcab8b64d:
      title: The Ganges Mahāmudrā Instructions
      parent: Advice
    2ca174d02d984661ba558eadf82ee7df:
      title: Aspiration of the Mahāmudrā of Definitive Meaning
      parent: Aspiration Prayers
    1757130987df4248adba637a3245f01c:
      title: 'A Casket of Sacred Dharma: Stages of Meditation on Dependent Arising'
      parent: Commentaries
    424472289cc14df3abf1e3c971bea6d6:
      title: The Concise Mahāmudrā Preliminaries Arranged for Recitation
      parent: Preliminaries
    3f8f58904ece4bc8bc55c901ccc9a358:
      title: 'The Excellent Path of Definitive Meaning: An Unmistaken Expression of
        the Definitive Mahāmudrā'
      parent: Songs
created_at: '2022-03-01T04:32:39.534907'
last_modified_at: '2022-03-01T04:32:39.534910'
